export const SET_PLAYER_STATUS = 'SET_PLAYER'

export const ADD_PLAY_LIST = 'ADD_PLAY_LIST'
export const DELETE_PALY_LIST = 'DELETE_PALY_LIST'
export const UPDATE_PLAY_LIST = 'UPDATE_PLAY_LIST'

export const SET_CURRENT_SONG = 'SET_CURRENT_SONG'
